theme: jekyll-theme-primer
title: Report: Predicting Murders in US Metropolitans 
description: Keeping Italian Olives Pure!
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
