theme: jekyll-theme-primer
title: Report: Predicting Murders in US Metropolitans
description: CS109a Final Project Report on Predicting Murders in US Metropolitans
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
